global proc int testExport(string $parent,
							string $action,
							string $initialSettings,
							string $resultCallback )
{
	int $ret;
	
	
	if($action == "post")
	{
		setParent $parent;
		ColumnLayout -adj true;
		string $on = uiRes("testExport.uOn");
		string $off = uiRes("testExport.uOff");
		
		radioButtonGrp
				-label uiRes("testExport.uSmooth")
				-nrb 2 -cw3 175 75 75
				-labelArray2 $on $off objGroups;
		$ret = 1;
	}
	return $ret;
}