#ifndef __TITAN__HH
#define __TITAN__HH

#include "TiPrerequisites.h"

#include "TiSharedPtr.h"
#include "TiDataStream.h"
#include "TiConsoleDebugger.h"
#include "TiColor.h"
#include "TiMath.h"
#include "TiResourceGroupMgr.h"
#include "TiFileSystemMgr.h"

#include "TiException.h"
#include "TiOverlayElement.h"
#include "TiOverlayMgr.h"
#include "TiOverlayPanelElement.h"
#include "TiOverlayTextElement.h"
#include "TiRenderWindow.h"
#include "TiRenderer.h"
#include "TiRoot.h"
#include "TiSceneMgr.h"

#include "TiMatrix3.h"
#include "TiMatrix4.h"
#include "TiVector2.h"
#include "TiVector3.h"
#include "TiVector4.h"
#include "TiManualObject.h"
#include "TiHelperMethods.h"
#include "TiSceneNode.h"
#include "TiCamera.h"
#include "TiFrustum.h"
#include "Timer.h"

#include "TiConfigFile.h"
#include "TiTextureMgr.h"
#include "TiIteratorWrapper.h"

#include "TiQuadtreeSceneMgr.h"
#include "TiBaseTerrain.h"
#include "TiBaseTerrain.h"
#include "TiBaseTerrainSection.h"
#include "TiChunkTerrain.h"
#include "TiChunkTerrainSection.h"
#include "TiGeoTerrain.h"
#include "TiGeoTerrainSection.h"

#include "TiShader.h"
#include "TiShaderParams.h"
#include "TiShaderUnit.h"
#include "TiShaderMgr.h"
#include "TiTexture.h"
#include "TiTextureMgr.h"
#include "TiTextureUnit.h"
#include "TiPass.h"
#include "TiMaterial.h"
#include "TiMaterialMgr.h"

#endif